config/routes.rb
Testexpe::Application.routes.draw do
  resources :presents

  resources :items

  resources :products

  resources :categories

  resources :shops

  match ':controller(/:action(/:id(.:format)))'
end

app/models/present.rb
class Present < ActiveRecord::Base


belongs_to :item
attr_protected :item_id



end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  # GET /presents
  # GET /presents.xml
  def index
    @presents = Present.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @presents }
    end
  end

  # GET /presents/1
  # GET /presents/1.xml
  def show
    @present = Present.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @present }
    end
  end

  # GET /presents/new
  # GET /presents/new.xml
  def new
    
    
    @itemid = params[:id]
    @products = Product.find_by_id(params[:prod_id]) 
    @present = Present.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @present }
    end
  end




  # POST /presents
  # POST /presents.xml



  def create
    @present = Present.new(params[:present])
    
    respond_to do |format|
      if @present.save
        format.html { redirect_to(@present, :notice => 'Present was successfully created.') }
        format.xml  { render :xml => @present, :status => :created, :location => @present }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @present.errors, :status => :unprocessable_entity }
      end
    end
  end


  # GET /presents/1/edit
  def edit
    @present = Present.find(params[:id])
   

    respond_to do |format|
	 format.js 
    end	

  end



  # PUT /presents/1
  # PUT /presents/1.xml
  #  Will actually create a new record for each updated present
  def update
      


      @present = Present.new(params[:present])
      @present.item_id = params[:present_item_id]
 
    respond_to do |format|
      if @present.save
       # format.html { redirect_to(@present, :notice => 'Present was successfully created.') }
        #format.xml  { render :xml => @present, :status => :created, :location => @present }
	format.html  { redirect_to (items_path) }
    else
        format.html { render :action => "new" }
        format.xml  { render :xml => @present.errors, :status => :unprocessable_entity }
      end
    end


    #@present = Present.find(params[:id])

    #respond_to do |format|
    #  if @present.update_attributes(params[:present])
     #   format.html { redirect_to(@present, :notice => 'Present was successfully updated.') }
      #  format.xml  { head :ok }
     # else
      #  format.html { render :action => "edit" }
      #  format.xml  { render :xml => @present.errors, :status => :unprocessable_entity }
     # end
   # end

  end

  # DELETE /presents/1
  # DELETE /presents/1.xml
  def destroy
    @present = Present.find(params[:id])
    @present.destroy

    respond_to do |format|
      format.html { redirect_to(presents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/presents/_form.html.erb
<%= form_for(@present) do |f| %>
  <% if @present.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
      <% @present.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
   <%= hidden_field_tag :present_item_id, @present.item_id %>
 </div>
  <div class="field">
   <%= hidden_field_tag :present_quantity_left2, @present.quantity_left %>
 </div>
  <div class="field">
    How much have you eaten out of <%= h(@present.quantity_left) %> today?<br />
    <%= f.text_field :quantity_left , :size => 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
    <div class="actions">
    <%= submit_tag("Reset", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
  </div>

<% end %>

<%= link_to 'Back', items_path %>

<script type="text/javascript" >
    $("#present_quantity_left").blur(function () { 
       var value = $("#present_quantity_left2").val();
       var value2 = $(this).val();
       $(this).val(value - value2);
 });
</script>

app/views/presents/edit.html.erb
<%= title "Editing Quantity Remaining for Item-" + @present.item.product.name %>

<%= render 'form' %>

app/views/presents/edit.js.erb
('#presentss').replacewith('<h2>Something big here</h2>');

app/views/presents/index.html.erb
<%= title "Listing Presents" %>

<table>
  <tr>
    <th>Item</th>
    <th>Quantity left</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @presents.each do |present| %>
  <tr>
    <td><%= present.item_id %></td>
    <td><%= present.quantity_left %></td>
    <td><%= link_to 'Show', present %></td>
    <td><%= link_to 'Edit', edit_present_path(present) %></td>
    <td><%= link_to 'Destroy', present, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Present', new_present_path %>

app/views/presents/new.html.erb
<%= title "New Present" %>

<%= render 'form' %>

<%= link_to 'Back', presents_path %>

app/views/presents/show.html.erb
<%= title "Showing Present-" @present.item.product.name %>
<p id="notice"><%= notice %></p>

<p>

  <b>Item:</b>
   <%= image_tag @present.item.product.product_img.url(:thumb) %>
    <%=	@present.item.product.name %>

    <%= collection_select :nil, :id, @products, @products, :prompt => "Select an Item" %>


</p>

<p>
  <b>Quantity left:</b>
  <%= @present.quantity_left %>
</p>


<%= link_to 'Edit', edit_present_path(@present) %> |
<%= link_to 'Back', presents_path %>